<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Localization\en.json" />
    <None Remove="Localization\es.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Localization\en.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Localization\es.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Imagekit" Version="5.0.0" />
    <PackageReference Include="MailKit" Version="4.11.0" />
    <PackageReference Include="MimeKit" Version="4.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WTE.TintTrack.Common.Application\WTE.TintTrack.Application.Shared.csproj" />
    <ProjectReference Include="..\WTE.TintTrack.Common\WTE.TintTrack.Common.csproj" />
  </ItemGroup>

</Project>
