// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WTE.TintTrack.Business.Infrastructure.DataPersistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20241108045007_AddedContactOwnership")]
    partial class AddedContactOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditLogId")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActionDate");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 8, 12, 50, 6, 880, DateTimeKind.Local).AddTicks(8523))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContactId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("City");

                    b.Property<string>("Company")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Company");

                    b.Property<int>("ContactType")
                        .HasColumnType("int")
                        .HasColumnName("ContactType");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Country");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 8, 12, 50, 6, 881, DateTimeKind.Local).AddTicks(574))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FullName");

                    b.Property<bool?>("Imported")
                        .HasColumnType("bit")
                        .HasColumnName("Imported");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Mobile");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Phone");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("StateOrRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Street");

                    b.Property<string>("Tags")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Tags");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Website");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.ContactOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContactOwnershipId")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 8, 12, 50, 6, 881, DateTimeKind.Local).AddTicks(4111))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("UserCode");

                    b.Property<bool?>("UserIsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("UserIsOwner");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactOwnerships", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.ContactOwnership", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Contact", "Contact")
                        .WithMany("ContactOwners")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Contact", b =>
                {
                    b.Navigation("ContactOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
