// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WTE.TintTrack.Business.Infrastructure;

#nullable disable

namespace WTE.TintTrack.Business.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20241119104142_CodedBusinessEntities")]
    partial class CodedBusinessEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditLogId")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActionDate");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 40, 969, DateTimeKind.Local).AddTicks(3701))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContactId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AddressLine2");

                    b.Property<string>("AltPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AltPhone");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("City");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<int>("ContactType")
                        .HasColumnType("int")
                        .HasColumnName("ContactType");

                    b.Property<string>("CountryISOCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CountryISOCode");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 34, DateTimeKind.Local).AddTicks(985))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("FullName");

                    b.Property<bool?>("Imported")
                        .HasColumnType("bit")
                        .HasColumnName("Imported");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("JobTitle");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Mobile");

                    b.Property<string>("Notes")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("StreetAddress");

                    b.PrimitiveCollection<string>("Tags")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Tags");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("Website");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AddressLine2");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("City");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<string>("CountryISOCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CountryISOCode");

                    b.Property<int>("CustomerLevel")
                        .HasColumnType("int")
                        .HasColumnName("CustomerLevel");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 40, 976, DateTimeKind.Local).AddTicks(3934))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("StreetAddress");

                    b.HasKey("Id");

                    b.ToTable("Customers", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerContactId")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 35, DateTimeKind.Local).AddTicks(4181))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int")
                        .HasColumnName("RelationshipType");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerOwnershipId")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 40, 972, DateTimeKind.Local).AddTicks(5311))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("UserCode");

                    b.Property<bool?>("UserIsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("UserIsOwner");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOwnerships", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerPropertyId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerPropertyDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 40, 978, DateTimeKind.Local).AddTicks(6823))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int")
                        .HasColumnName("PropertyType");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerPropertyDetailsId")
                        .IsUnique();

                    b.ToTable("CustomerProperties", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerPropertyDetailsId")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CustomerPropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 40, 983, DateTimeKind.Local).AddTicks(4038))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator<int>("PropertyType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InvoiceId")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("AmountPaid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 44, DateTimeKind.Local).AddTicks(452))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InvoiceDate");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("InvoiceNumber");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Invoices", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectId")
                        .HasColumnOrder(0);

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("ActualCost");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 42, DateTimeKind.Local).AddTicks(373))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("EstimatedCost");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ProjectName");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Projects", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProposalId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 39, DateTimeKind.Local).AddTicks(6082))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ProposalNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProposalNumber");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("ScopeOfWork")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("ScopeOfWork");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Terms");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Proposals", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 19, 18, 41, 41, 37, DateTimeKind.Local).AddTicks(657))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Description");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("IsAccepted");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("QuoteDate");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("QuoteNumber");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Quotes", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.ArchitecturalPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSecurityFilm")
                        .HasColumnType("bit");

                    b.Property<string>("WindowSizeInFeet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.AutomotivePropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDefrostLines")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Mileage")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TintType")
                        .HasColumnType("int");

                    b.Property<string>("Trim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.CommercialPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSecurityGlass")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSoundproofing")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUVProtection")
                        .HasColumnType("bit");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.CustomPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("CustomGlassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomizationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.EnergyEfficientPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("CoatingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasInsulatedGlass")
                        .HasColumnType("bit");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.GlassFilmPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<double>("FilmThickness")
                        .HasColumnType("float");

                    b.Property<string>("FilmType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTinted")
                        .HasColumnType("bit");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.OtherPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("OtherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.OutdoorPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<bool>("HasSafetyFeatures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeatherResistant")
                        .HasColumnType("bit");

                    b.Property<string>("OutdoorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.ResidentialPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<bool>("HasEnergyEfficientWindows")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPrivacyTint")
                        .HasColumnType("bit");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.SignagePropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("BrandingDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBacklit")
                        .HasColumnType("bit");

                    b.Property<string>("SignageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.PropertyDetails.SpecialtyPropertyDetails", b =>
                {
                    b.HasBaseType("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails");

                    b.Property<string>("ApplicationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFireResistant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmartGlass")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialtyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomerPropertyDetails", "dbo");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerContact", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Contact", "Contact")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerOwnership", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerOwnerships")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerProperty", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerProperties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails", "CustomerPropertyDetails")
                        .WithOne("CustomerProperty")
                        .HasForeignKey("WTE.TintTrack.Business.Domain.Entities.CustomerProperty", "CustomerPropertyDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerPropertyDetails");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Project", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Customer", null)
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId");

                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Proposal", "Proposal")
                        .WithMany("Projects")
                        .HasForeignKey("ProposalId");

                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Quote", "Quote")
                        .WithMany("Projects")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Proposal", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Quote", "Quote")
                        .WithMany("Proposals")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Quote", b =>
                {
                    b.HasOne("WTE.TintTrack.Business.Domain.Entities.Customer", "Customer")
                        .WithMany("Quotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Contact", b =>
                {
                    b.Navigation("CustomerContacts");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerContacts");

                    b.Navigation("CustomerOwnerships");

                    b.Navigation("CustomerProperties");

                    b.Navigation("Projects");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.CustomerPropertyDetails", b =>
                {
                    b.Navigation("CustomerProperty")
                        .IsRequired();
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Project", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Proposal", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WTE.TintTrack.Business.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
