<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IEntityRecordValidator.cs" />
    <Compile Remove="Messaging\_GenericApiResponseWrapper.cs" />
    <Compile Remove="Validator\ValidationErrorResponse.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.0" />
    <PackageReference Include="SMEAppHouse.Core.Patterns.Repo" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\_Business\WTE.TintTrack.Business.Domain\WTE.TintTrack.Business.Domain.csproj" />
    <ProjectReference Include="..\WTE.TintTrack.Common\WTE.TintTrack.Common.csproj" />
    <ProjectReference Include="..\WTE.TintTrack.Domain.Shared\WTE.TintTrack.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
