<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\CommercialOffersConfig\**" />
    <Compile Remove="Configurations\old\**" />
    <Compile Remove="Configurations\SalesAndQuotingConfig\**" />
    <Compile Remove="Repositories\SalesAndQuoting\**" />
    <Compile Remove="Repositories\_old\**" />
    <EmbeddedResource Remove="Configurations\CommercialOffersConfig\**" />
    <EmbeddedResource Remove="Configurations\old\**" />
    <EmbeddedResource Remove="Configurations\SalesAndQuotingConfig\**" />
    <EmbeddedResource Remove="Repositories\SalesAndQuoting\**" />
    <EmbeddedResource Remove="Repositories\_old\**" />
    <None Remove="Configurations\CommercialOffersConfig\**" />
    <None Remove="Configurations\old\**" />
    <None Remove="Configurations\SalesAndQuotingConfig\**" />
    <None Remove="Repositories\SalesAndQuoting\**" />
    <None Remove="Repositories\_old\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Repositories\ContactOwnershipRepository.cs" />
    <Compile Remove="Repositories\CustomerOwnershipRepository.cs" />
    <Compile Remove="Repositories\ProjectMilestoneRepository.cs" />
    <Compile Remove="Repositories\ProjectRepository.cs" />
    <Compile Remove="Repositories\SubscriptionPlanFeatureRepository.cs" />
    <Compile Remove="Repositories\SubscriptionPlanRepository.cs" />
    <Compile Remove="Repositories\SubscriptionPromoDiscountRepository.cs" />
    <Compile Remove="Repositories\TenantRepository.cs" />
    <Compile Remove="Repositories\TenantSubscriptionInvoiceRepository.cs" />
    <Compile Remove="Repositories\TenantSubscriptionPaymentRepository.cs" />
    <Compile Remove="Repositories\TenantSubscriptionRepository.cs" />
    <Compile Remove="Repositories\UserBillingProfileRepository.cs" />
    <Compile Remove="Repositories\UserRepository.cs" />
    <Compile Remove="Repositories\UserTenantRepository.cs" />
    <Compile Remove="Repositories\VehicleRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.json" />
    <None Remove="ResetDB.SQL" />
    <None Remove="SqlFiles\DropAllFKs.sql" />
    <None Remove="SqlFiles\DropAllPKs.sql" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Configurations\CommercialOffersConfig\EstimateConfiguration.cs" />
    <Compile Include="Configurations\CommercialOffersConfig\OfferHistoryConfiguration.cs" />
    <Compile Include="Configurations\CommercialOffersConfig\OfferMilestoneConfiguration.cs" />
    <Compile Include="Configurations\CommercialOffersConfig\OfferRecipientConfiguration.cs" />
    <Compile Include="Configurations\CommercialOffersConfig\ProposalConfiguration.cs" />
    <Compile Include="Configurations\CommercialOffersConfig\QuoteConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\ContractConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\ProjectConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\ProjectMilestoneConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\WorkOrderAssignmentConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\WorkOrderConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\WorkOrderItemConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\WorkOrderLogConfiguration.cs" />
    <Compile Include="Configurations\SalesAndQuotingConfig\WorkOrderLogPhotoConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SqlFiles\DropAllFKs.sql" />
    <EmbeddedResource Include="SqlFiles\DropAllPKs.sql" />
    <EmbeddedResource Include="SqlFiles\DropAllTbls.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\_Common\WTE.TintTrack.Common.Application\WTE.TintTrack.Application.Shared.csproj" />
    <ProjectReference Include="..\..\_Common\WTE.TintTrack.Common\WTE.TintTrack.Common.csproj" />
    <ProjectReference Include="..\WTE.TintTrack.Business.Domain\WTE.TintTrack.Business.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\TintServiceRepos\" />
  </ItemGroup>

</Project>
