// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WTE.TintTrack.Core.Infrastructure;

#nullable disable

namespace WTE.TintTrack.Core.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125133614_AddedAppFeatureAccess")]
    partial class AddedAppFeatureAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 223, DateTimeKind.Local).AddTicks(3326))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("Description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ApplicationFeatures", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationFeatureRoleAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ApplicationFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CRUDActionAccess")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 234, DateTimeKind.Local).AddTicks(811))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFeatureId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationFeatureRoleAccesses", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryISOCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 13, 36, 13, 236, DateTimeKind.Utc).AddTicks(6062));

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 13, 36, 13, 236, DateTimeKind.Utc).AddTicks(8844));

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ReasonArchived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.CustomerInquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Budget");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConsultationDate");

                    b.Property<string>("ConsultationDetails")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("ConsultationDetails");

                    b.Property<int>("ContactMethod")
                        .HasColumnType("int")
                        .HasColumnName("ContactMethod");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CustomerCode");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 239, DateTimeKind.Local).AddTicks(991))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("FollowUpNeeded");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<int>("PropertyType")
                        .HasColumnType("int")
                        .HasColumnName("PropertyType");

                    b.Property<string>("ProposalCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProposalCode");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid?>("SalesRepresentativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("SpecialRequests");

                    b.Property<int?>("TintType")
                        .HasColumnType("int")
                        .HasColumnName("TintType");

                    b.HasKey("Id");

                    b.HasIndex("SalesRepresentativeId");

                    b.ToTable("CustomerInquiries", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int")
                        .HasColumnName("BillingCycle");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 244, DateTimeKind.Local).AddTicks(1424))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("PlanCode");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 249, DateTimeKind.Local).AddTicks(1650))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Percentage");

                    b.Property<string>("PlanDiscountCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("PlanDiscountCode");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlanDiscounts", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 245, DateTimeKind.Local).AddTicks(7966))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FeatureCode");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlanFeatures", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanFeatureAssociation", b =>
                {
                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionPlanFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubscriptionPlanId", "SubscriptionPlanFeatureId");

                    b.HasIndex("SubscriptionPlanFeatureId");

                    b.ToTable("SubscriptionPlanFeatureAssociations", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ConnectionString");

                    b.Property<string>("CountryOfHost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CountryOfHost");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 250, DateTimeKind.Local).AddTicks(6189))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("Domain")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Domain");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("LogoImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LogoImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TenantCode");

                    b.Property<int>("TenantStatus")
                        .HasColumnType("int")
                        .HasColumnName("TenantStatus");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 253, DateTimeKind.Local).AddTicks(8617))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionStatus");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSubscriptions", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("BillingProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Currency");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 255, DateTimeKind.Local).AddTicks(5440))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar")
                        .HasColumnName("InvoiceCode");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar")
                        .HasColumnName("InvoiceNo");

                    b.Property<int>("InvoiceStatus")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceStatus");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<decimal?>("LateFeeAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LateFeeAmount");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Notes");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("TenantSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillingProfileId");

                    b.HasIndex("TenantSubscriptionId");

                    b.ToTable("TenantSubscriptionInvoices", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 258, DateTimeKind.Local).AddTicks(20))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatus");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("TenantSubscriptionPayments", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 242, DateTimeKind.Local).AddTicks(3730))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expiration");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar")
                        .HasColumnName("RefreshToken");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserBillingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar")
                        .HasColumnName("BillingAddress");

                    b.Property<string>("BillingDetailsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("BillingDetailsJson");

                    b.Property<int>("BillingProfileType")
                        .HasColumnType("int")
                        .HasColumnName("BillingProfileType");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 259, DateTimeKind.Local).AddTicks(8795))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBillingProfiles", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 261, DateTimeKind.Local).AddTicks(4982))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("IsDefault");

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UserIsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("UserIsOwner");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTenants", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenantInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 252, DateTimeKind.Local).AddTicks(3226))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EmailAddress");

                    b.Property<int>("InvitationSource")
                        .HasColumnType("int")
                        .HasColumnName("InvitationSource");

                    b.Property<int>("InvitationStatus")
                        .HasColumnType("int")
                        .HasColumnName("InvitationStatus");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTenantInvitations", "dbo");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("DateTime2")
                        .HasColumnOrder(511);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 11, 25, 21, 36, 13, 263, DateTimeKind.Local).AddTicks(2285))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnOrder(510);

                    b.Property<string>("ReasonArchived")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("nvarchar(132)")
                        .HasColumnOrder(511);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserTenantId");

                    b.ToTable("UserTenantRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationFeature", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationFeature", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationFeatureRoleAccess", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationFeature", "ApplicationFeature")
                        .WithMany()
                        .HasForeignKey("ApplicationFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationFeature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.CustomerInquiry", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", "SalesRepresentative")
                        .WithMany("CustomerInquiries")
                        .HasForeignKey("SalesRepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SalesRepresentative");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanDiscount", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPlanDiscounts")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanFeatureAssociation", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanFeature", "SubscriptionPlanFeature")
                        .WithMany("SubscriptionPlanFeatureAssociations")
                        .HasForeignKey("SubscriptionPlanFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPlanFeatureAssociations")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("SubscriptionPlanFeature");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionInvoice", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.UserBillingProfile", "BillingProfile")
                        .WithMany()
                        .HasForeignKey("BillingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.TenantSubscription", "TenantSubscription")
                        .WithMany("TenantSubscriptionInvoices")
                        .HasForeignKey("TenantSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingProfile");

                    b.Navigation("TenantSubscription");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionPayment", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionInvoice", "TenantSubscriptionInvoice")
                        .WithMany("TenantSubscriptionPayments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenantSubscriptionInvoice");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.Token", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tokens")
                        .HasForeignKey("TenantId");

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserBillingProfile", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserBillingProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenant", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenantInvitation", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserTenantInvitations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserTenantInvitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenantRole", b =>
                {
                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WTE.TintTrack.Core.Domain.Entities.UserTenant", "UserTenant")
                        .WithMany("UserTenantRoles")
                        .HasForeignKey("UserTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserTenant");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CustomerInquiries");

                    b.Navigation("Tokens");

                    b.Navigation("UserBillingProfiles");

                    b.Navigation("UserTenantInvitations");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("SubscriptionPlanDiscounts");

                    b.Navigation("SubscriptionPlanFeatureAssociations");

                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.SubscriptionPlanFeature", b =>
                {
                    b.Navigation("SubscriptionPlanFeatureAssociations");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("TenantSubscriptions");

                    b.Navigation("Tokens");

                    b.Navigation("UserTenantInvitations");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscription", b =>
                {
                    b.Navigation("TenantSubscriptionInvoices");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.TenantSubscriptionInvoice", b =>
                {
                    b.Navigation("TenantSubscriptionPayments");
                });

            modelBuilder.Entity("WTE.TintTrack.Core.Domain.Entities.UserTenant", b =>
                {
                    b.Navigation("UserTenantRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
