<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ModelAbstractions\**" />
    <EmbeddedResource Remove="ModelAbstractions\**" />
    <None Remove="ModelAbstractions\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Helpers\IncludePredicateConverter.cs" />
    <Compile Remove="Interfaces\ITenantContext.cs" />
    <Compile Remove="Interfaces\IUnitOfWork.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.1.2" />
  </ItemGroup>

</Project>
